### ISSUE TITLE
Expectaions Bug

### ISSUE THREAD

**Issue by CaptainJon** [alinGmail/LiveMock#21]
After switching expections to another page (there are many expectations)，users can not modify expetations that comes begin with page 2, I suppose it is because the list was rendered by loop and items were binded with key of index, if we modify data from page 2, data from page 1 can get affected. 

thus, if there are many expecations, it is not functional anymore.

**Comment by alinGmail** [comment]
yes，because the update of expectation use the index of the table row number, so i do not work in page 2. I will see how to fix it.

**Comment by alinGmail** [comment]
the bug was fixed by https://github.com/alinGmail/LiveMock/commit/2b64f2b6898f173afdc531ed50a79a1f231d7bde

**Comment by CaptainJon** [comment]
> the bug was fixed by [2b64f2b](https://github.com/alinGmail/LiveMock/commit/2b64f2b6898f173afdc531ed50a79a1f231d7bde)

glad to hear that, are you going to publish a release?
