### ISSUE TITLE
Encounter error while trying to run electron

### ISSUE THREAD

**Issue by CaptainJon** [alinGmail/LiveMock#22]
yarn workspace desktop start

![image](https://github.com/alinGmail/LiveMock/assets/51065061/4fb17ada-2e13-4cd9-a0ef-e86d000c118b)

**Comment by alinGmail** [comment]
Can you provide more information? For example how to reproduce this problem

**Comment by alinGmail** [comment]
try to build the core sub project first, cd to the core folder, run 'yarn run tsc'

**Comment by CaptainJon** [comment]
> try to build the core sub project first, cd to the core folder, run 'yarn run tsc'

yeah, it works now, then how to start the electron? i tried cd to the desktop fold and run " yarn start" or "yarn dev", the electron app shows but nothing on it. it is blank. can you show the step?

**Comment by alinGmail** [comment]
you need to build the project first, in the desktop folder, run 'yarn run tsc' , then  'yarn run vite'  and then 'yarn run electron'.

**Comment by CaptainJon** [comment]
> you need to build the project first, in the desktop folder, run 'yarn run tsc' , then 'yarn run vite' and then 'yarn run electron'.

nice, it's working now, i guess if i want to build the electron, just run "yarn run build"?

**Comment by CaptainJon** [comment]
> you need to build the project first, in the desktop folder, run 'yarn run tsc' , then 'yarn run vite' and then 'yarn run electron'.

when I try "yarn run electron"， the apps shows and works well, but the command shows errors below:

![image](https://github.com/alinGmail/LiveMock/assets/51065061/21c01ac6-f785-490f-8b1a-312f4ee58360)

when I tried to start the server, error pops out:
![image](https://github.com/alinGmail/LiveMock/assets/51065061/feccca45-4660-4025-9e7f-0df3320c2a5f)

and the commands adds some warnning or error i dunno:
![image](https://github.com/alinGmail/LiveMock/assets/51065061/8f1aa8d2-c422-4e9c-90d5-afaf7ddff0af)

**Comment by alinGmail** [comment]
i have no idea about the ssl error.  but it look like have nothing to do with the server start fail.
you can change the projectHandler.js code in dist-electron folder. in line 137. it may be look like the code above

` server.once("error", (error) => {
                // res.status(500);
                throw new common_1.ServerError(500, "server start fail");
 });
`
add some code to log the error to see what happen.
