### ISSUE TITLE
Can you give an example about how to set Custom Response with MockJs handler?

### ISSUE THREAD

**Issue by CaptainJon** [alinGmail/LiveMock#28]
just as title says

**Comment by alinGmail** [comment]
create a custom response and the content handler chose moskjs, for more mockjs example see http://mockjs.com/examples.html 
<img width="489" alt="Screenshot 2024-07-10 at 23 45 54" src="https://github.com/alinGmail/LiveMock/assets/102706292/c80dab62-6d17-42b3-a1cb-e3bbc77b14f1">
